### ISSUE TITLE
Libvirt network config doesn't handle DHCP section

### ISSUE THREAD

**Issue by BubaVV** [virt-lightning/virt-lightning#239]
IP address defined in yaml file hasn't saved to libvirt network config. In case of VM stopped by some reason (e.g. host reboot) it loses IP lease after some time. If request address by DHCP service, it will be random from network range. Alternative to it is some universal way to define static IP

**Comment by goneri** [comment]
Hi @BubaVV!

Yes, we don't record the dynamic IP "by design". You can set a static IP with an `ipv4` key in the `networks` list: https://github.com/virt-lightning/virt-lightning#example-a-virt-lightningyaml-file

Another example, it's a Jinja2 file, but it generates a .yaml at the end. Just ignore the `"{{ bla }}"` blocks:
https://github.com/goneri/deploy-vmware-ci/blob/master/libvirt/virt-lightning.j2
